spring.application.name=api-gateway
server.port=8080

#Eureka client
eureka.client.service-url.default-zone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}


#learne-service routes
spring.cloud.gateway.routes[0].id=learne-service
spring.cloud.gateway.routes[0].uri=lb://LEARNE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/answers/**, /api/v1/courses/**, /api/v1/courses_enrollment/**, /api/v1/exams/**, /api/v1/materials/**, /api/v1/notes/**, /api/v1/payments/**, /api/v1/questions/**, /api/v1/sections/**, /api/v1/tutorials_courses/**, /api/v1/tutorials_reservated/**, /api/v1/units**

#learne-service swagger routes
spring.cloud.gateway.routes[1].id=learne-service-swagger
spring.cloud.gateway.routes[1].uri=lb://LEARNE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/learne/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/learne(?<segment>/?.*), $\{segment}

#profile-service routes
spring.cloud.gateway.routes[2].id=profile-service
spring.cloud.gateway.routes[2].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/users/**

#profile-service swagger routes
spring.cloud.gateway.routes[3].id=profile-service-swagger
spring.cloud.gateway.routes[3].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/profile/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/profile(?<segment>/?.*), $\{segment}

# Log
logging.level.root=info
logging.level.org.springframework.cloud.gateway=trace
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=info
